coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "src/**/*.test.ts"
  - "src/**/*.spec.ts"
  - "src/test.ts"
  - "jest.config.js"
  - "coverage/**/*"
  - "node_modules/**/*" 